#!/usr/bin/env ruby

# Pretty much an exact copy of
# https://github.com/codegangsta/dotfiles/blob/master/bootstrap

require "fileutils"

def link(path, link_name)
  path = File.expand_path path
  link_name = File.expand_path link_name

  puts "linking #{link_name}..."

  if File.symlink? link_name
    puts "\tRemoving symlink..."
    FileUtils.rm link_name
  elsif File.exists? link_name
    puts "\tSkipping because a file already exists."
    return
  end

  FileUtils.ln_s(path, link_name)
end

puts "Bootstrapping dotfiles..."
link "~/Code/Grok/dotfiles/bash_aliases", "~/.bash_aliases"
link "~/Code/Grok/dotfiles/bash_commit_template", "~/.bash_commit_template"
link "~/Code/Grok/dotfiles/bash_git_autocomplete", "~/.bash_git_autocomplete"
link "~/Code/Grok/dotfiles/bash_git_prompt", "~/.bash_git_prompt"
link "~/Code/Grok/dotfiles/bash_git_syntax_aware", "~/.bash_git_syntax_aware"
link "~/Code/Grok/dotfiles/bash_profile", "~/.bash_profile"
link "~/Code/Grok/dotfiles/bash_prompt", "~/.bash_prompt"
link "~/Code/Grok/dotfiles/bash_ps1_functions", "~/.bash_ps1_functions"
link "~/Code/Grok/dotfiles/bash_shell_variables", "~/.bash_shell_variables"
link "~/Code/Grok/dotfiles/bashrc", "~/.bashrc"
link "~/Code/Grok/dotfiles/editorconfig", "~/.editorconfig"
link "~/Code/Grok/dotfiles/gemrc", "~/.gemrc"
link "~/Code/Grok/dotfiles/gitconfig", "~/.gitconfig"
link "~/Code/Grok/dotfiles/gitignore_global", "~/.gitignore_global"
link "~/Code/Grok/dotfiles/vimrc", "~/.vimrc"

# directories
# link "~/dotfiles/vim", "~/.vim"

puts "done"
